#pragma config(Sensor, S2, Touch, sensorEV3_Touch)
#pragma config(Sensor, S1, US, sensorEV3_Ultrasonic)
#pragma config(Motor, motorB, MotorB, tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor, motorA, MotorA, tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define Near 10

task main()
{
	resetBumpedValue(S2);
	while (true) {
		if (getUSDistance(S1)<Near && getMotorRPM(MotorA) > 0 && getMotorRPM(MotorB) > 0){
			setMotorSpeed(MotorA,-30);
			setMotorSpeed(MotorB,30);
		}
		else{
			if (getBumpedValue(S2) %2!=0){
			setMotorSpeed(MotorA,20);
			setMotorSpeed(MotorB,20);
			}
			else{
			setMotorSpeed(MotorA,0);
			setMotorSpeed(MotorB,0);
			}
		}
	}
}
