#pragma config(Sensor, S3, Touch, sensorEV3_Touch)
#pragma config(Sensor, S4, US, sensorEV3_Ultrasonic)
#pragma config(Motor, motorB, MotorB, tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor, motorA, MotorA, tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor, motorC, MotorC, tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define Near 4

task main()
{
	resetBumpedValue(S3);
	while (true) {
		if (getUSDistance(S4)<Near && getMotorRPM(MotorA) > 0 && getMotorRPM(MotorB) > 0){
			while(1){
			setMotorSpeed(MotorA,0);
			setMotorSpeed(MotorB,0);
			if(getColorName(S2)==colorGreen){
			  setMotorSpeed(MotorC,-10);
				}
			if(getColorName(S2)==colorRed){
			  	setMotorSpeed(MotorC,0);
			 		 }
			if(getColorName(S2)==colorBlue){
				setMotorSpeed(MotorC,30);
				delay(1000);
				setMotorSpeed(MotorC,0);
				break;
		  }
			}
		}
		else{
			if (getBumpedValue(S3) %2!=0){
			setMotorSpeed(MotorA,10);
			setMotorSpeed(MotorB,10);
			}
			else{
			setMotorSpeed(MotorA,0);
			setMotorSpeed(MotorB,0);
			}
		}
	}
}
